-- AlterTable
ALTER TABLE "soilMoistureData" ALTER COLUMN "data" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "voltageData" ALTER COLUMN "data" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "waterLevelData" ALTER COLUMN "data" SET DATA TYPE DOUBLE PRECISION;
